import { SellerCommandCards, SellerFilterBar, SellerPageHeader, SellerPageState, SellerSection, SellerStatusBadge, getSection, type SellerViewProps } from "@/components/seller/seller-page-primitives";

const roleLabels = ["대표 관리자", "상품 담당자", "출고 담당자", "성과 조회자"];
const roleKeys = ["owner", "product", "fulfillment", "analyst"] as const;

export function SellerMembersView({ csrfToken, page, search }: SellerViewProps) {
  const permissions = getSection(page, "permissions"); const audit = getSection(page, "audit");
  return <div className="seller-workspace seller-members"><SellerPageHeader page={page} /><SellerPageState page={page} /><SellerSection title="구성원"><SellerFilterBar page={page} resultCount={page.rows.length} search={search} /><div className="seller-table-scroll"><table className="seller-members-table"><caption>구성원 역할과 접속 상태</caption><thead><tr><th scope="col">구성원</th><th scope="col">역할</th><th scope="col">주요 권한</th><th scope="col">상태</th><th scope="col">최근 접속</th></tr></thead><tbody>{page.rows.map((row, index) => <tr key={row.id ?? row.name}><th scope="row"><span className="seller-avatar">{row.name.slice(0, 1)}</span>{row.name}<small>{index === 0 ? "kim***@dropmong.com" : "member***@dropmong.com"}</small></th><td><label className="sr-only" htmlFor={`role-${row.id}`}>{row.name} 역할</label><select defaultValue={row.role} id={`role-${row.id}`}>{roleLabels.map((role) => <option key={role}>{role}</option>)}</select></td><td>{row.access}</td><td><SellerStatusBadge>{row.state}</SellerStatusBadge></td><td>{index ? "어제 18:05" : "오늘 14:32"}</td></tr>)}</tbody></table></div></SellerSection>
    <div className="seller-members-grid"><SellerSection title="역할별 권한" description="전체 허용, 일부 허용, 접근 불가를 문구와 기호로 구분합니다."><div className="seller-table-scroll"><table className="seller-permission-matrix"><caption>역할별 메뉴 권한표</caption><thead><tr><th scope="col">업무</th>{roleLabels.map((role) => <th key={role} scope="col">{role}</th>)}</tr></thead><tbody>{permissions.map((permission) => <tr key={permission.menu}><th scope="row">{permission.menu}</th>{roleKeys.map((key) => <td key={key}><span aria-label={accessLabel(permission[key])} className={`permission-${permission[key]}`}>{permission[key] === "all" ? "✓" : permission[key] === "read" ? "−" : ""}</span></td>)}</tr>)}</tbody></table></div><p className="seller-matrix-legend"><span><i className="permission-all">✓</i> 전체 허용</span><span><i className="permission-read">−</i> 일부 허용</span><span><i className="permission-none" /> 접근 불가</span></p></SellerSection><SellerSection title="최근 권한 변경"><ol className="seller-audit-list">{audit.map((item) => <li key={`${item.target}-${item.at}`}><span className="seller-avatar">{item.actor.slice(0, 1)}</span><div><strong>{item.actor} · {item.target}</strong><p>{item.change}</p></div><time>{item.at}</time></li>)}</ol></SellerSection></div><SellerCommandCards csrfToken={csrfToken} page={page} title="구성원과 권한 작업" />
  </div>;
}

function accessLabel(value?: string): string { return value === "all" ? "전체 허용" : value === "read" ? "일부 허용" : "접근 불가"; }
