package catalog

// Element ties executable code to the authoritative BC document identifier.
type Element struct {
	ID      string
	Name    string
	Handler string
}

var Aggregates = []Element{
	{ID: "AGG.A.19-01", Name: "CouponCampaign", Handler: "campaign.Repository"},
	{ID: "AGG.A.19-02", Name: "CouponCodeBatch", Handler: "couponcode.Repository"},
	{ID: "AGG.A.19-03", Name: "UserCoupon", Handler: "usercoupon.Repository"},
	{ID: "AGG.A.19-04", Name: "CouponRedemption", Handler: "redemption.Repository"},
	{ID: "AGG.A.19-05", Name: "BulkCouponIssueJob", Handler: "bulk.Repository"},
	{ID: "AGG.A.19-06", Name: "CouponIssueRequest", Handler: "issuerequest.Repository"},
	{ID: "AGG.A.19-07", Name: "CouponOperationalControl", Handler: "operations.Repository"},
	{ID: "AGG.A.19-08", Name: "CouponEventRecovery", Handler: "recovery.Repository"},
}

var Commands = []Element{
	{ID: "CMD.A.19-01", Name: "쿠폰 정책 등록", Handler: "CampaignService.RegisterPolicy"},
	{ID: "CMD.A.19-02", Name: "선착순 발급 조건 설정", Handler: "CampaignService.ConfigureIssuance"},
	{ID: "CMD.A.19-03", Name: "판매자·제휴 쿠폰 검토", Handler: "CampaignService.Review"},
	{ID: "CMD.A.19-04", Name: "쿠폰 정책 변경", Handler: "CampaignService.ChangePolicy"},
	{ID: "CMD.A.19-05", Name: "쿠폰 수령 요청", Handler: "IssuanceService.Claim"},
	{ID: "CMD.A.19-06", Name: "쿠폰 코드 등록", Handler: "IssuanceService.RedeemCode"},
	{ID: "CMD.A.19-07", Name: "사용자 쿠폰 발급", Handler: "IssuanceService.Issue"},
	{ID: "CMD.A.19-08", Name: "대량 발급 작업 등록", Handler: "OperationsService.RegisterBulkJob"},
	{ID: "CMD.A.19-09", Name: "쿠폰 조건·할인 금액 검증", Handler: "RedemptionService.Validate"},
	{ID: "CMD.A.19-10", Name: "쿠폰 사용 예약", Handler: "RedemptionService.Reserve"},
	{ID: "CMD.A.19-11", Name: "쿠폰 사용 확정", Handler: "RedemptionService.Confirm"},
	{ID: "CMD.A.19-12", Name: "쿠폰 사용 예약 해제", Handler: "RedemptionService.Release"},
	{ID: "CMD.A.19-13", Name: "쿠폰 발급 요청 생성", Handler: "IssuanceService.CreateRequest"},
	{ID: "CMD.A.19-14", Name: "쿠폰 발급 실패 기록", Handler: "IssuanceService.RecordFailure"},
	{ID: "CMD.A.19-15", Name: "쿠폰 사용 회수", Handler: "RedemptionService.Reclaim"},
	{ID: "CMD.A.19-16", Name: "쿠폰 코드 등록 확정", Handler: "IssuanceService.ConfirmCode"},
	{ID: "CMD.A.19-17", Name: "쿠폰 코드 예약 해제", Handler: "IssuanceService.ReleaseCode"},
	{ID: "CMD.A.19-18", Name: "대량 발급 결과 집계", Handler: "OperationsService.AggregateBulkResult"},
	{ID: "CMD.A.19-19", Name: "쿠폰 발급 재처리", Handler: "IssuanceService.Retry"},
	{ID: "CMD.A.19-20", Name: "쿠폰 운영 중지 적용", Handler: "OperationsService.ApplyStop"},
	{ID: "CMD.A.19-21", Name: "쿠폰 사용 업무 재처리", Handler: "OperationsService.RequestRecovery"},
	{ID: "CMD.A.19-22", Name: "쿠폰 발급 최종 실패 처리", Handler: "IssuanceService.FinalizeFailure"},
	{ID: "CMD.A.19-23", Name: "쿠폰 발급 성공 기록", Handler: "IssuanceService.RecordSuccess"},
	{ID: "CMD.A.19-24", Name: "사용자 쿠폰 만료", Handler: "OperationsService.ExpireCoupon"},
	{ID: "CMD.A.19-25", Name: "쿠폰 사용 최종 실패 처리", Handler: "OperationsService.FinalizeRecovery"},
	{ID: "CMD.A.19-26", Name: "쿠폰 발급 수량 예약", Handler: "CampaignService.ReserveQuantity"},
	{ID: "CMD.A.19-27", Name: "쿠폰 발급 수량 확정", Handler: "CampaignService.ConfirmQuantity"},
	{ID: "CMD.A.19-28", Name: "쿠폰 발급 수량 예약 해제", Handler: "CampaignService.ReleaseQuantity"},
	{ID: "CMD.A.19-29", Name: "쿠폰 발급 거절 기록", Handler: "IssuanceService.Reject"},
	{ID: "CMD.A.19-30", Name: "쿠폰 발급 처리 대기 기록", Handler: "IssuanceService.MarkPending"},
	{ID: "CMD.A.19-31", Name: "쿠폰 읽기 전용 안내 적용", Handler: "OperationsService.ApplyReadOnlyNotice"},
	{ID: "CMD.A.19-32", Name: "쿠폰 사용 원본 Command 재실행", Handler: "RedemptionService.Replay"},
	{ID: "CMD.A.19-33", Name: "쿠폰 이벤트 재처리 결과 기록", Handler: "OperationsService.RecordRecoveryResult"},
	{ID: "CMD.A.19-34", Name: "쿠폰 사용 이벤트 처리 실패 기록", Handler: "OperationsService.RecordProcessingFailure"},
}

var Events = []Element{
	{ID: "EVT.A.19-01", Name: "쿠폰 정책 등록됨", Handler: "coupon.policy.registered"},
	{ID: "EVT.A.19-02", Name: "쿠폰 검토 요청됨", Handler: "coupon.review.requested"},
	{ID: "EVT.A.19-03", Name: "쿠폰 승인됨", Handler: "coupon.approved"},
	{ID: "EVT.A.19-04", Name: "쿠폰 반려됨", Handler: "coupon.rejected"},
	{ID: "EVT.A.19-05", Name: "쿠폰 검토 보류됨", Handler: "coupon.review.held"},
	{ID: "EVT.A.19-06", Name: "쿠폰 정책 변경됨", Handler: "coupon.policy.changed"},
	{ID: "EVT.A.19-07", Name: "쿠폰 발급 요청 접수됨", Handler: "coupon.issue.accepted"},
	{ID: "EVT.A.19-08", Name: "쿠폰 발급 거절됨", Handler: "coupon.issue.rejected"},
	{ID: "EVT.A.19-09", Name: "사용자 쿠폰 발급됨", Handler: "coupon.user_coupon.issued"},
	{ID: "EVT.A.19-10", Name: "쿠폰 발급 처리 실패함", Handler: "coupon.issue.failed_retryable"},
	{ID: "EVT.A.19-11", Name: "쿠폰 발급 최종 실패함", Handler: "coupon.issue.failed_final"},
	{ID: "EVT.A.19-12", Name: "쿠폰 코드 등록 요청이 검증됨", Handler: "coupon.code.validated"},
	{ID: "EVT.A.19-13", Name: "쿠폰 코드 등록됨", Handler: "coupon.code.redeemed"},
	{ID: "EVT.A.19-14", Name: "쿠폰 코드 예약이 해제됨", Handler: "coupon.code.released"},
	{ID: "EVT.A.19-15", Name: "쿠폰 코드 등록이 거절됨", Handler: "coupon.code.rejected"},
	{ID: "EVT.A.19-16", Name: "대량 발급 작업 등록됨", Handler: "coupon.bulk_issue.registered"},
	{ID: "EVT.A.19-17", Name: "대량 발급 작업 완료됨", Handler: "coupon.bulk_issue.completed"},
	{ID: "EVT.A.19-18", Name: "대량 발급 작업 실패함", Handler: "coupon.bulk_issue.completed_with_failures"},
	{ID: "EVT.A.19-19", Name: "쿠폰 적용 가능 확인됨", Handler: "coupon.redemption.eligible"},
	{ID: "EVT.A.19-20", Name: "쿠폰 적용 거절됨", Handler: "coupon.redemption.ineligible"},
	{ID: "EVT.A.19-21", Name: "쿠폰 사용 예약됨", Handler: "coupon.redemption.reserved"},
	{ID: "EVT.A.19-22", Name: "쿠폰 사용 확정됨", Handler: "coupon.redemption.confirmed"},
	{ID: "EVT.A.19-23", Name: "쿠폰 사용 예약 해제됨", Handler: "coupon.redemption.released"},
	{ID: "EVT.A.19-24", Name: "쿠폰 사용 회수됨", Handler: "coupon.redemption.reclaimed"},
	{ID: "EVT.A.19-25", Name: "쿠폰 운영 중지 적용됨", Handler: "coupon.operational_stop.applied"},
	{ID: "EVT.A.19-26", Name: "쿠폰 이벤트 재처리 완료됨", Handler: "coupon.recovery.completed"},
	{ID: "EVT.A.19-27", Name: "쿠폰 이벤트 재처리 실패함", Handler: "coupon.recovery.retry_failed"},
	{ID: "EVT.A.19-28", Name: "쿠폰 비용 귀속 기록됨", Handler: "coupon.cost_attribution.recorded"},
	{ID: "EVT.A.19-29", Name: "쿠폰 발급 요청 완료됨", Handler: "coupon.issue.completed"},
	{ID: "EVT.A.19-30", Name: "쿠폰 이벤트 최종 실패 처리됨", Handler: "coupon.recovery.failed_final"},
	{ID: "EVT.A.19-31", Name: "사용자 쿠폰 만료됨", Handler: "coupon.user_coupon.expired"},
	{ID: "EVT.A.19-32", Name: "쿠폰 발급 수량 예약됨", Handler: "coupon.quantity.reserved"},
	{ID: "EVT.A.19-33", Name: "쿠폰 발급 수량 예약 거절됨", Handler: "coupon.quantity.rejected"},
	{ID: "EVT.A.19-34", Name: "쿠폰 발급 수량 확정됨", Handler: "coupon.quantity.confirmed"},
	{ID: "EVT.A.19-35", Name: "쿠폰 발급 수량 예약 해제됨", Handler: "coupon.quantity.released"},
	{ID: "EVT.A.19-36", Name: "쿠폰 발급 처리 대기됨", Handler: "coupon.issue.pending"},
	{ID: "EVT.A.19-37", Name: "쿠폰 발급 재처리 대기됨", Handler: "coupon.issue.retry_pending"},
	{ID: "EVT.A.19-38", Name: "쿠폰 읽기 전용 안내 적용됨", Handler: "coupon.read_only_notice.applied"},
	{ID: "EVT.A.19-39", Name: "쿠폰 사용 이벤트 재실행 대기됨", Handler: "coupon.recovery.retry_pending"},
	{ID: "EVT.A.19-40", Name: "쿠폰 사용 이벤트 처리 실패 기록됨", Handler: "coupon.recovery.failure_recorded"},
	{ID: "EVT.A.19-41", Name: "쿠폰 사용 재실행 결과 판정됨", Handler: "coupon.redemption.replay_decided"},
}

var Policies = []Element{
	{ID: "POLICY.A.19-01", Name: "발급 주체·비용 부담 명시", Handler: "RequireIssuerAndFunding"},
	{ID: "POLICY.A.19-02", Name: "판매자 소유 범위 제한", Handler: "VerifySellerOwnership"},
	{ID: "POLICY.A.19-03", Name: "쿠폰 승인 게이트", Handler: "RequireCampaignApproval"},
	{ID: "POLICY.A.19-04", Name: "발급 자격·수량 제한", Handler: "CheckIssueEligibility"},
	{ID: "POLICY.A.19-05", Name: "코드 등록 유효성", Handler: "CheckCouponCode"},
	{ID: "POLICY.A.19-06", Name: "주문 스냅샷 검증", Handler: "VerifyOrderSnapshot"},
	{ID: "POLICY.A.19-07", Name: "정책 버전 적용", Handler: "SelectPolicyVersion"},
	{ID: "POLICY.A.19-08", Name: "운영 중지 우선", Handler: "CheckOperationalStop"},
	{ID: "POLICY.A.19-09", Name: "발급 요청 후속 처리", Handler: "RequestUserCouponIssue"},
	{ID: "POLICY.A.19-10", Name: "코드 등록 보상 처리", Handler: "CompleteOrReleaseCode"},
	{ID: "POLICY.A.19-11", Name: "발급 요청 생성", Handler: "CreateCommonIssueRequest"},
	{ID: "POLICY.A.19-12", Name: "대량 발급 결과 반영", Handler: "AggregateBulkResult"},
	{ID: "POLICY.A.19-13", Name: "발급 수량 예약", Handler: "RequestQuantityReservation"},
	{ID: "POLICY.A.19-14", Name: "발급 실패 재처리 결정", Handler: "RequestIssueRetry"},
	{ID: "POLICY.A.19-15", Name: "발급 성공 요청 완료", Handler: "CompleteIssueRequest"},
	{ID: "POLICY.A.19-16", Name: "시스템 자동 지급 요청 변환", Handler: "ConvertSystemGrant"},
	{ID: "POLICY.A.19-17", Name: "만료 시각 도달 처리", Handler: "RequestCouponExpiry"},
	{ID: "POLICY.A.19-18", Name: "만료 쿠폰 예약 해제", Handler: "RequestExpiredReservationRelease"},
	{ID: "POLICY.A.19-19", Name: "발급 수량 결과 반영", Handler: "ApplyQuantityResult"},
	{ID: "POLICY.A.19-20", Name: "발급 처리 대기 전환", Handler: "MarkIssuePending"},
	{ID: "POLICY.A.19-21", Name: "실패 원본 업무 재실행", Handler: "RequestUseReplay"},
	{ID: "POLICY.A.19-22", Name: "재처리 결과 반영", Handler: "ApplyRecoveryResult"},
}
