import Link from "next/link";

import { SellerDetailDrawer } from "@/components/seller/seller-detail-drawer";
import { SellerCommandCards, SellerFilterBar, SellerMetricGrid, SellerPageHeader, SellerPageState, SellerSection, SellerStatusBadge, getCloseHref, getSection, type SellerViewProps } from "@/components/seller/seller-page-primitives";

export function SellerIssuesView({ csrfToken, page, search }: SellerViewProps) {
  const timeline = getSection(page, "timeline");
  return <div className="seller-workspace"><SellerPageHeader page={page} /><SellerPageState page={page} /><SellerMetricGrid columns={3} metrics={[...page.metrics, { label: "처리 대기", value: "8건", note: "판매자 확인 필요" }]} /><SellerFilterBar page={page} resultCount={page.rows.length} search={search} /><SellerSection title="운영 이슈 목록" description="주문·드롭·정산 연결과 표준 사유 코드를 함께 확인합니다."><div className="seller-table-scroll"><table className="seller-issues-table"><caption>운영 이슈와 처리 상태</caption><thead><tr><th scope="col">이슈</th><th scope="col">유형</th><th scope="col">관련 항목</th><th scope="col">사유 코드</th><th scope="col">접수일</th><th scope="col">처리 상태</th></tr></thead><tbody>{page.rows.map((row) => <tr key={row.id ?? row.issue}><th scope="row"><Link data-panel-trigger={row.id} href={`?issueId=${row.id}`}>{row.issue}</Link></th><td>{row.type}</td><td>{row.related}</td><td>{row.reason}</td><td>{row.opened}</td><td><SellerStatusBadge>{row.state}</SellerStatusBadge></td></tr>)}</tbody></table></div></SellerSection><SellerCommandCards csrfToken={csrfToken} page={page} title="운영 이슈 신고" />
    {page.panel ? <SellerDetailDrawer closeHref={getCloseHref("/seller/issues", search)} panelId={page.panel.id} title="이슈 상세"><div className="seller-issue-detail"><dl><div><dt>이슈 번호</dt><dd>{page.panel.id}</dd></div><div><dt>유형</dt><dd>출고 지연</dd></div><div><dt>관련 주문</dt><dd>ORD-240712-1038</dd></div><div><dt>처리 상태</dt><dd><SellerStatusBadge>처리 중</SellerStatusBadge></dd></div></dl><label>판매자 메모<textarea defaultValue="출고 예정일을 안내했으나 아직 출고되지 않아 확인을 요청합니다." rows={4} /></label><div className="seller-attachments"><strong>첨부</strong><button type="button">＋ 증빙 파일 추가</button><span>출고확인서.pdf · 284KB</span></div><h3>처리 타임라인</h3><ol className="seller-timeline">{timeline.map((item, index) => <li className={index === 1 ? "is-current" : ""} key={item.title}><span /><div><strong>{item.title}</strong><small>{item.at}</small><p>{item.note}</p></div></li>)}</ol><Link className="seller-button seller-button--secondary" href="/seller/orders">관련 주문 보기</Link><p>{page.panel.body}</p></div></SellerDetailDrawer> : null}
  </div>;
}
