import { SellerDataUnavailable, SellerFilterBar, SellerMetricGrid, SellerPageHeader, SellerPageState, SellerSection, getSection, type SellerViewProps } from "@/components/seller/seller-page-primitives";

export function SellerAnalyticsView({ page, search }: SellerViewProps) {
  const funnel = getSection(page, "funnel"); const products = getSection(page, "products"); const coupons = getSection(page, "couponEffect"); const refunds = getSection(page, "refunds");
  return <div className="seller-workspace seller-analytics"><SellerPageHeader page={page} /><SellerPageState page={page} /><SellerFilterBar page={page} resultCount={page.rows.length} search={search} /><SellerMetricGrid columns={5} metrics={[...page.metrics, { label: "조회", value: funnel[0]?.value ?? "확인 불가", note: "집계 완료" }, { label: "구매 시도", value: funnel[2]?.value ?? "확인 불가", note: "집계 완료" }, { label: "구매 성공", value: funnel[3]?.value ?? "확인 불가", note: "집계 완료" }]} />
    <div className="seller-analytics-grid"><SellerSection title="판매 퍼널" description="각 단계는 이전 단계 대비 전환율입니다.">{funnel.length ? <><ol className="seller-funnel">{funnel.map((item, index) => <li key={item.stage} style={{ width: `${100 - index * 13}%` }}><span>{item.stage}</span><strong>{Number(item.value).toLocaleString("ko-KR")}</strong><small>{item.rate}</small></li>)}</ol><table className="seller-sr-table"><caption>판매 퍼널 데이터</caption><thead><tr><th scope="col">단계</th><th scope="col">수치</th><th scope="col">전환율</th></tr></thead><tbody>{funnel.map((item) => <tr key={item.stage}><th scope="row">{item.stage}</th><td>{item.value}</td><td>{item.rate}</td></tr>)}</tbody></table></> : <SellerDataUnavailable label="판매 퍼널" />}</SellerSection><SellerSection title="최근 7일 성과 추이" description="실선은 집계 완료, 점선은 실시간 추정입니다.">{page.rows.length ? <><div aria-hidden="true" className="seller-trend-lines">{page.rows.map((row, index) => <span key={row.date} style={{ height: `${35 + index * 18}%` }}><i /><small>{row.date}</small></span>)}</div><details className="seller-chart-table"><summary>추이 데이터 표로 보기</summary><table><caption>최근 7일 성과</caption><thead><tr>{page.columns.map((column) => <th key={column.key} scope="col">{column.label}</th>)}</tr></thead><tbody>{page.rows.map((row) => <tr key={row.date}>{page.columns.map((column, index) => index === 0 ? <th key={column.key} scope="row">{row[column.key]}</th> : <td key={column.key}>{row[column.key]}</td>)}</tr>)}</tbody></table></details></> : <SellerDataUnavailable label="성과 추이" />}</SellerSection></div>
    <div className="seller-analytics-bottom"><SellerSection title="상위 상품·옵션">{products.length ? <div className="seller-table-scroll"><table><caption>전환율 상위 상품</caption><thead><tr><th scope="col">상품·옵션</th><th scope="col">조회</th><th scope="col">구매 시도</th><th scope="col">구매 성공</th><th scope="col">전환율</th></tr></thead><tbody>{products.map((item) => <tr key={item.name}><th scope="row">{item.name}</th><td>{item.views}</td><td>{item.attempts}</td><td>{item.purchases}</td><td className="is-success">{item.rate}</td></tr>)}</tbody></table></div> : <SellerDataUnavailable label="상품 성과" />}</SellerSection><SellerSection title="쿠폰 효과" description="인과 효과가 아닌 상관 비교입니다.">{coupons.length ? <div className="seller-coupon-effect">{coupons.map((item) => <article key={item.label}><span>{item.label}</span><strong>{item.value}</strong><small>{item.note}</small></article>)}</div> : <SellerDataUnavailable label="쿠폰 효과" />}</SellerSection><SellerSection title="취소·환불">{refunds.length ? <div className="seller-refund-bars">{refunds.map((item) => <div key={item.reason}><span>{item.reason}</span><i><b style={{ width: `${item.value}%` }} /></i><strong>{item.value}%</strong><small>{item.amount}</small></div>)}</div> : <SellerDataUnavailable label="취소·환불" />}</SellerSection></div>
  </div>;
}
