import Link from "next/link";

import { SellerDetailDrawer } from "@/components/seller/seller-detail-drawer";
import { SellerCommandCards, SellerEmptyState, SellerFilterBar, SellerMetricGrid, SellerPageHeader, SellerPageState, SellerSection, SellerStatusBadge, SellerThumbnail, getCloseHref, type SellerViewProps } from "@/components/seller/seller-page-primitives";

export function SellerProductsView({ csrfToken, page, search }: SellerViewProps) {
  return <div className="seller-workspace"><SellerPageHeader page={page} /><SellerPageState page={page} /><SellerMetricGrid columns={3} metrics={page.metrics} /><SellerFilterBar page={page} resultCount={page.rows.length} search={search} />
    <SellerSection title="등록 상품" description="옵션·재고·연결 드롭을 한 행에서 확인합니다.">{page.rows.length ? <div className="seller-table-scroll"><table className="seller-products-table"><caption>판매 상품 목록</caption><thead><tr><th scope="col">상품</th><th scope="col">카테고리</th><th scope="col">SKU·옵션</th><th scope="col">판매가</th><th scope="col">재고</th><th scope="col">연결 드롭</th><th scope="col">업데이트</th><th scope="col">관리</th></tr></thead><tbody>{page.rows.map((row, index) => <tr key={row.id ?? row.name}><th scope="row"><span className="seller-product-cell"><SellerThumbnail label={row.name} tone={index} /><span><strong>{row.name}</strong><SellerStatusBadge>{row.state}</SellerStatusBadge></span></span></th><td>{row.category}</td><td><strong>{row.sku ?? "확인 불가"}</strong><small>{row.option ?? "옵션 없음"}</small></td><td className="seller-number">{row.price}</td><td className={Number(row.stock) < 20 ? "seller-number is-danger" : "seller-number"}>{row.stock ?? "-"}</td><td>{row.drops ?? "-"}</td><td>{row.updated ?? "-"}</td><td><Link className="seller-table-action" data-panel-trigger={row.id} href={`?${withPanel(search, "productId", row.id)}`}>미리보기</Link></td></tr>)}</tbody></table></div> : <SellerEmptyState filtered={search.size > 0} message={page.emptyMessage} />}</SellerSection><SellerCommandCards csrfToken={csrfToken} page={page} title="상품 저장" />
    {page.panel ? <SellerDetailDrawer closeHref={getCloseHref("/seller/products", search)} panelId={page.panel.id} title={page.panel.title}><div className="seller-preview-card"><SellerThumbnail label={page.panel.title} tone={2} /><span><SellerStatusBadge>구매자 노출 미리보기</SellerStatusBadge><h3>{page.rows.find((row) => row.id === page.panel?.id)?.name ?? page.panel.title}</h3><p>{page.panel.body}</p><dl><div><dt>판매가</dt><dd>{page.rows.find((row) => row.id === page.panel?.id)?.price ?? "확인 불가"}</dd></div><div><dt>재고</dt><dd>{page.rows.find((row) => row.id === page.panel?.id)?.stock ?? "확인 불가"}</dd></div></dl><button className="seller-button seller-button--secondary" type="button">편집 항목 확인</button></span></div></SellerDetailDrawer> : null}
  </div>;
}

function withPanel(search: URLSearchParams, key: string, value?: string): string { const next = new URLSearchParams(search); if (value) next.set(key, value); return next.toString(); }
