import Link from "next/link";

import { SellerDetailDrawer } from "@/components/seller/seller-detail-drawer";
import { SellerEmptyState, SellerFilterBar, SellerMetricGrid, SellerPageHeader, SellerPageState, SellerSection, SellerStatusBadge, getCloseHref, type SellerViewProps } from "@/components/seller/seller-page-primitives";

export function SellerSettlementsView({ page, search }: SellerViewProps) {
  return <div className="seller-workspace"><SellerPageHeader page={page} /><SellerPageState page={page} /><SellerFilterBar page={page} resultCount={page.rows.length} search={search} /><SellerMetricGrid metrics={[...page.metrics, { label: "정산 확정", value: "42,180,000원", note: "지난 기간" }, { label: "차감 예정", value: "1,230,000원", note: "환불·분쟁" }]} />
    <SellerSection title="정산 내역" description="매출에서 쿠폰 부담·수수료·차감액을 분리해 확인합니다.">{page.rows.length ? <div className="seller-table-scroll"><table className="seller-settlement-table"><caption>기간별 정산 금액과 상태</caption><thead><tr><th scope="col">판매 기간</th><th scope="col">대상 주문</th><th scope="col">매출</th><th scope="col">쿠폰 부담</th><th scope="col">수수료</th><th scope="col">차감액</th><th scope="col">예상 지급액</th><th scope="col">상태</th></tr></thead><tbody>{page.rows.map((row, index) => <tr key={row.id ?? row.period}><th scope="row"><Link data-panel-trigger={row.id} href={`?settlementId=${row.id}`}>{row.period}</Link></th><td>{index ? "342건" : "1,278건"}</td><td>{index ? "4,120,000원" : "4,280,000원"}</td><td>-280,000원</td><td>-640,000원</td><td>{row.deduction}</td><td className="seller-number"><strong>{row.amount}</strong></td><td><SellerStatusBadge>{row.state}</SellerStatusBadge></td></tr>)}</tbody></table></div> : <SellerEmptyState filtered={search.size > 0} message={page.emptyMessage} />}</SellerSection>
    {page.panel ? <SellerDetailDrawer closeHref={getCloseHref("/seller/settlements", search)} panelId={page.panel.id} title="정산 상세"><div className="seller-settlement-detail"><div className="seller-alert seller-alert--warning"><strong>정산 보류 사유</strong><span>반품 처리 중인 주문 2건이 반영되면 다음 정산에서 확정됩니다.</span></div><dl><div><dt>판매 기간</dt><dd>6월 24일~30일</dd></div><div><dt>매출</dt><dd>4,120,000원</dd></div><div><dt>쿠폰 부담</dt><dd>-280,000원</dd></div><div><dt>수수료</dt><dd>-640,000원</dd></div><div><dt>차감 예정</dt><dd>-42,000원</dd></div><div className="is-total"><dt>예상 지급액</dt><dd>3,158,000원</dd></div></dl><Link className="seller-button seller-button--secondary" href="/seller/orders">관련 주문 확인</Link><p>{page.panel.body}</p></div></SellerDetailDrawer> : null}
  </div>;
}
