import { SellerOnboardingForm } from "@/components/seller/seller-action-form";
import { SellerCommandCards, SellerPageHeader, SellerPageState, SellerSection, SellerStatusBadge, getSection, type SellerViewProps } from "@/components/seller/seller-page-primitives";

export function SellerStoreView({ csrfToken, page }: SellerViewProps) {
  const preview = getSection(page, "preview")[0];
  const onboarding = page.title === "판매자 등록";
  return <div className="seller-workspace seller-store"><SellerPageHeader page={page} /><SellerPageState page={page} />{onboarding ? <SellerSection title="판매자 등록 정보" description="판매자 계정과 대표 관리자 membership을 먼저 만듭니다."><SellerOnboardingForm csrfToken={csrfToken} /></SellerSection> : <><nav aria-label="설정 구분" className="seller-tabs"><a aria-current="page" href="#seller-account">판매자 정보</a><a href="#store-brand">스토어 브랜딩</a><a href="#store-policy">배송·교환·환불</a></nav><div className="seller-store-grid"><div><SellerSection title="판매자 정보" className="seller-form-section"><div className="seller-form-grid"><label>판매자명<input defaultValue="드롭몽 스튜디오" /></label><label>판매자 유형<select defaultValue="brand"><option value="brand">브랜드 공식 스토어</option></select></label><label>담당자 연락처<input defaultValue="010-1234-5678" type="tel" /></label></div></SellerSection><SellerSection title="스토어 기본 정보" className="seller-form-section"><div className="seller-form-grid"><label>스토어명<input defaultValue="드롭몽 스튜디오" maxLength={30} /></label><label className="seller-form-wide">스토어 소개<textarea defaultValue="정품만을 엄선해 합리적인 가격으로 제공합니다." maxLength={100} rows={3} /></label></div><div className="seller-upload-grid"><button type="button"><span aria-hidden="true">＋</span><strong>로고 이미지</strong><small>JPG, PNG, WEBP · 최대 2MB</small></button><button type="button"><span aria-hidden="true">＋</span><strong>커버 이미지</strong><small>1920×400px 권장 · 최대 5MB</small></button></div></SellerSection><SellerSection title="사업자 인증"><div className="seller-verification"><div><small>사업자등록번호</small><strong>123-45-67890</strong></div><div><small>대표자명</small><strong>김드롭</strong></div><div><small>사업자 상태</small><SellerStatusBadge>인증 완료</SellerStatusBadge></div><div><small>인증일</small><strong>2026.01.15</strong></div></div></SellerSection><SellerSection title="기본 정책" className="seller-form-section"><label>배송 정책<textarea defaultValue="평일 14시 이전 주문은 당일 출고합니다." rows={3} /></label><label>교환·환불 정책<textarea defaultValue="수령 후 7일 이내 교환·환불을 요청할 수 있습니다." rows={3} /></label></SellerSection></div><aside><SellerSection title="구매자 화면 미리보기" actions={<SellerStatusBadge>실시간 미리보기</SellerStatusBadge>}><div className="seller-store-preview"><div className="seller-store-preview__cover"><span>D</span></div><div className="seller-store-preview__profile"><span>D</span><div><h3>{preview?.store ?? "스토어 정보 확인 불가"}</h3><SellerStatusBadge>공식 스토어</SellerStatusBadge></div></div><p>{preview?.introduction ?? "원천 계약에서 미리보기 정보를 제공하지 않았습니다."}</p><dl><div><dt>팔로워</dt><dd>{preview?.followers ?? "-"}</dd></div><div><dt>상품</dt><dd>{preview?.products ?? "-"}</dd></div><div><dt>평점</dt><dd>{preview?.rating ?? "-"}</dd></div></dl><div className="seller-preview-products">{["후디", "에코백", "스니커즈", "볼캡"].map((item) => <span key={item}><i />{item}</span>)}</div></div></SellerSection></aside></div><SellerCommandCards csrfToken={csrfToken} page={page} title="판매자와 스토어 저장" /></>}
  </div>;
}
