import Link from "next/link";

import { SellerEmptyState, SellerFilterBar, SellerMetricGrid, SellerPageHeader, SellerPageState, SellerProgress, SellerSection, SellerStatusBadge, SellerThumbnail, type SellerViewProps } from "@/components/seller/seller-page-primitives";

export function SellerDropsView({ page, search }: SellerViewProps) {
  return <div className="seller-workspace"><SellerPageHeader page={page} /><SellerPageState page={page} /><SellerMetricGrid columns={3} metrics={page.metrics} /><SellerFilterBar page={page} resultCount={page.rows.length} search={search} />
    <SellerSection title="드롭 목록" description="초안·검수·판매 상태는 서로 다른 상태로 표시합니다.">{page.rows.length ? <><div className="seller-table-scroll"><table className="seller-operations-table"><caption>드롭 목록과 재고 진행률</caption><thead><tr><th scope="col">드롭</th><th scope="col">초안</th><th scope="col">검수</th><th scope="col">판매</th><th scope="col">오픈</th><th scope="col">재고</th><th scope="col">주문</th><th scope="col">작업</th></tr></thead><tbody>{page.rows.map((row, index) => <tr key={row.id ?? row.name}><th scope="row"><span className="seller-product-cell"><SellerThumbnail label={row.name} tone={index} /><span><strong>{row.name}</strong><small>{row.id ?? "식별자 확인 불가"}</small></span></span></th><td><SellerStatusBadge>{row.draft}</SellerStatusBadge></td><td><SellerStatusBadge>{row.review}</SellerStatusBadge></td><td><SellerStatusBadge>{row.sales}</SellerStatusBadge></td><td>{row.open ?? "확인 불가"}</td><td><SellerProgress label="재고 소진" value={Number(row.inventory ?? 0)} /></td><td className="seller-number">{row.orders ?? "-"}</td><td><Link className="seller-table-action" href={`/seller/drops/${row.id ?? "new"}/edit`}>관리</Link></td></tr>)}</tbody></table></div><nav aria-label="드롭 목록 페이지" className="seller-pagination"><button aria-label="이전 페이지" disabled type="button">‹</button><a aria-current="page" href="?page=1">1</a><a href="?page=2">2</a><a href="?page=3">3</a><button aria-label="다음 페이지" type="button">›</button></nav></> : <SellerEmptyState filtered={search.size > 0} message={page.emptyMessage} />}</SellerSection>
  </div>;
}
