import Link from "next/link";

import { SellerDetailDrawer } from "@/components/seller/seller-detail-drawer";
import { SellerCommandCards, SellerEmptyState, SellerFilterBar, SellerMetricGrid, SellerPageHeader, SellerPageState, SellerProgress, SellerSection, SellerStatusBadge, getCloseHref, type SellerViewProps } from "@/components/seller/seller-page-primitives";

export function SellerCouponsView({ csrfToken, page, search }: SellerViewProps) {
  const tab = search.get("view") ?? "seller";
  return <div className="seller-workspace"><SellerPageHeader page={page} /><SellerPageState page={page} /><SellerMetricGrid metrics={page.metrics} /><SellerSection title="쿠폰·제휴 관리"><nav aria-label="쿠폰 종류" className="seller-tabs"><Link aria-current={tab === "seller" ? "page" : undefined} href="?view=seller">판매자 쿠폰</Link><Link aria-current={tab === "proposal" ? "page" : undefined} href="?view=proposal">제휴 쿠폰 제안</Link></nav><SellerFilterBar page={page} resultCount={page.rows.length} search={search} />{page.rows.length ? <div className="seller-table-scroll"><table className="seller-coupon-table"><caption>쿠폰 혜택과 비용 부담 및 성과</caption><thead><tr><th scope="col">쿠폰·제휴</th><th scope="col">혜택</th><th scope="col">적용 대상</th><th scope="col">비용 부담</th><th scope="col">성과</th><th scope="col">상태</th><th scope="col">관리</th></tr></thead><tbody>{page.rows.filter((row) => tab === "proposal" ? row.id?.startsWith("proposal") : !row.id?.startsWith("proposal")).map((row) => <tr key={row.id ?? row.name}><th scope="row">{row.name}</th><td>{row.benefit}</td><td>{row.scope}</td><td>{row.cost}</td><td><SellerProgress label={row.performance ?? "성과"} value={Number(row.performance?.match(/\d+/)?.[0] ?? 0)} /></td><td><SellerStatusBadge>{row.state}</SellerStatusBadge></td><td>{row.id?.startsWith("proposal") ? <Link className="seller-table-action" data-panel-trigger={row.id} href={`?view=proposal&proposalId=${row.id}`}>제안 보기</Link> : <button className="seller-table-action" type="button">관리</button>}</td></tr>)}</tbody></table></div> : <SellerEmptyState filtered={search.size > 0} message={page.emptyMessage} />}</SellerSection><SellerCommandCards csrfToken={csrfToken} page={page} title="쿠폰 저장" />
    {page.panel ? <SellerDetailDrawer closeHref={getCloseHref("/seller/coupons", search)} panelId={page.panel.id} title="제휴 쿠폰 제안"><div className="seller-proposal"><SellerStatusBadge>신규 제안</SellerStatusBadge><h3>브랜드 데이 공동 프로모션</h3><dl><div><dt>혜택</dt><dd>15% 할인</dd></div><div><dt>적용 대상</dt><dd>리넨 셔츠 2차</dd></div><div><dt>비용 부담</dt><dd>판매자 50% · 플랫폼 50%</dd></div><div><dt>응답 기한</dt><dd className="is-danger">3일 남음</dd></div></dl><p>{page.panel.body}</p><div><button className="seller-button seller-button--secondary" type="button">거절</button><button className="seller-button seller-button--primary" type="button">참여</button></div></div></SellerDetailDrawer> : null}
  </div>;
}
